### ISSUE TITLE
AWS Stack not working 

### ISSUE THREAD

**Issue by faraan** [mobilequickie/AmazonSpeechTranslator#1]
Hi I am trying to configure AWS as suggested in youtube video , but while creating stack I am getting this error 

S3 error: The specified bucket does not exist For more information check http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html

Please check , is you s3 configuration doesn't exist , 
if you share how to make this stack template , will be very helpful 

Thanks

**Comment by dmennis** [comment]
Hi, @faraan.

The CloudFormation template being used for the one-click deployment was hosted on an S3 bucket that has since been removed. I had a copy of the template and uploaded it here: https://github.com/mobilequickie/AmazonSpeechTranslator/blob/master/SpeechTranslator-CloudFormation-Cognito.yaml 

I'll create a new S3 bucket to host this template to re-enable one-click deploy at a later date. For now, run this manually using the CloudFormation Management Console.

Let me know if you have any issues!
